/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplopractica2;

import static ejemplopractica2.HistorialPedido.historiales;
import static ejemplopractica2.PreparacionPedido.productos;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author USUARIO
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public static Distancia[] distancias = new Distancia[50];
    public static int contadorDistancias;

    public String vehiculo;
    public String distancia;
    public String monto;
    public String creacion;
    public String entrega;

    public Inicio() {
        initComponents();
        //No se cambie el tamaño de la ventana
        this.setResizable(false);
        //Utilizado para visualizar en el centro la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegistroProductoBtn = new javax.swing.JButton();
        PedidoBtn = new javax.swing.JButton();
        HistorialBtn = new javax.swing.JButton();
        GuardarBtn = new javax.swing.JButton();
        ImportarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Inicio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        RegistroProductoBtn.setText("Registro de Productos");
        RegistroProductoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroProductoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RegistroProductoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 180, 40));

        PedidoBtn.setText("Preparación de Pedido");
        PedidoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedidoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PedidoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 180, 40));

        HistorialBtn.setText("Historial de Pedidos");
        HistorialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HistorialBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 40));

        GuardarBtn.setText("Guardar Información");
        GuardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 180, 40));

        ImportarBtn.setText("Importar Información");
        ImportarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportarBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ImportarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroProductoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroProductoBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistroProducto rp = new RegistroProducto();
        rp.setVisible(true);
    }//GEN-LAST:event_RegistroProductoBtnActionPerformed

    private void PedidoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedidoBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        PreparacionPedido pp = new PreparacionPedido();
        pp.setVisible(true);
    }//GEN-LAST:event_PedidoBtnActionPerformed

    private void HistorialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HistorialPedido hp = new HistorialPedido();
        hp.setVisible(true);
    }//GEN-LAST:event_HistorialBtnActionPerformed

    private void GuardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtnActionPerformed
        // TODO add your handling code here:

        /*Historial nuevoHistorial = new Historial(vehiculo, distancia, monto, creacion, entrega);
        int contadorHistoriales = HistorialPedido.contadorHistoriales;
        HistorialPedido.historiales[contadorHistoriales] = nuevoHistorial;
        HistorialPedido.contadorHistoriales++;*/
        try {
            FileOutputStream archivoh = new FileOutputStream("./Respaldo.txt");
            ObjectOutputStream salidah = new ObjectOutputStream(archivoh);
            salidah.writeObject(historiales);
            salidah.close();
            archivoh.close();
            System.out.println("Se ha respaldado su programa en: Respaldo.txt");
        } catch (Exception e) {
            System.out.println(e);
        }
        
        try {
            FileOutputStream archivop = new FileOutputStream("./RespaldoProductos.txt");
            ObjectOutputStream salidap = new ObjectOutputStream(archivop);
            salidap.writeObject(productos);
            salidap.close();
            archivop.close();
            System.out.println("Se ha respaldado su programa en: Respaldo.txt");
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_GuardarBtnActionPerformed

    private void ImportarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImportarBtnActionPerformed
        // TODO add your handling code here:

        try {
            FileInputStream archivoh = new FileInputStream("./Respaldo.txt");
            ObjectInputStream entradah = new ObjectInputStream(archivoh);
            Historial[] auxiliar = new Historial[50];
            auxiliar = (Historial[]) entradah.readObject();
            entradah.close();
            archivoh.close();

            for (int i = 0; i < auxiliar.length; i++) {
                Historial objh = new Historial(auxiliar[i].vehiculo, auxiliar[i].distancia, auxiliar[i].monto, auxiliar[i].creacion, auxiliar[i].entrega);
                historiales[i] = objh;
                HistorialPedido.contadorHistoriales++;
            }
            
            

        } catch (Exception e) {
            System.out.println(e);
        }
        
        try {
            FileInputStream archivop = new FileInputStream("./RespaldoProductos.txt");
            ObjectInputStream entradap = new ObjectInputStream(archivop);
            Producto[] auxiliarp = new Producto[50];
            auxiliarp = (Producto[]) entradap.readObject();
            entradap.close();
            archivop.close();

            for (int i = 0; i < auxiliarp.length; i++) {
                Producto objp = new Producto(auxiliarp[i].nombre, auxiliarp[i].precio);
                productos[i] = objp;
                PreparacionPedido.contadorProductos++;
            }
            
            

        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_ImportarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarBtn;
    private javax.swing.JButton HistorialBtn;
    private javax.swing.JButton ImportarBtn;
    private javax.swing.JButton PedidoBtn;
    private javax.swing.JButton RegistroProductoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
