/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejemplopractica2;

import javax.swing.JLabel;

/**
 *
 * @author USUARIO
 */
public class VerRecorridos extends javax.swing.JFrame {

    /**
     * Creates new form VerRecorridos
     */
    public VerRecorridos() {
        initComponents();
        //No se cambie el tamaño de la ventana
        this.setResizable(false);
        //Utilizado para visualizar en el centro la ventana
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DestinoLbl = new javax.swing.JLabel();
        Vehiculo2Lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Vehiculo1Lbl = new javax.swing.JLabel();
        Vehiculo3Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DestinoLbl.setBackground(new java.awt.Color(51, 51, 255));
        DestinoLbl.setOpaque(true);
        jPanel1.add(DestinoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 30, 570));

        Vehiculo2Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repartidor_ida.png"))); // NOI18N
        jPanel1.add(Vehiculo2Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 130));

        jButton1.setText("Iniciar Todos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, -1, -1));

        Vehiculo1Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repartidor_ida.png"))); // NOI18N
        jPanel1.add(Vehiculo1Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 130));

        Vehiculo3Lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/repartidor_ida.png"))); // NOI18N
        jPanel1.add(Vehiculo3Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Recorrido rec1 = new Recorrido(Vehiculo1Lbl, 2);
        Recorrido rec2 = new Recorrido(Vehiculo2Lbl, 10);
        Recorrido rec3 = new Recorrido(Vehiculo3Lbl, 5);

        rec1.start();
        rec2.start();
        rec3.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerRecorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerRecorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerRecorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerRecorridos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerRecorridos().setVisible(true);
            }
        });
    }
    /*
    public JLabel getVehiculo(){
        return Vehiculo1Lbl;
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel DestinoLbl;
    public static javax.swing.JLabel Vehiculo1Lbl;
    public static javax.swing.JLabel Vehiculo2Lbl;
    public static javax.swing.JLabel Vehiculo3Lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
